# Generated by Django 3.2.9 on 2021-12-10 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrationApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='job',
        ),
    ]
